### ISSUE TITLE
Port to Qt5

### ISSUE THREAD

**Issue by MartinAltmayer** [maestromusic/maestro#29]
End of lifetime for Qt 4.8 was extended by one year to 19th December 2015. 
http://blog.qt.io/blog/2014/11/27/qt-4-8-x-support-to-be-extended-for-another-year/

**Comment by supermihi** [comment]
We also should not hope to wait for pyside:

" As of 2015, The PySide project looks mostly dead and does not support Qt 5.

If you are looking for a long term solution, or one compatible with Qt 5, consider PyQt instead. "

(from the pyside homepage).

**Comment by supermihi** [comment]
There's now a branch qt5 with a working version of Maestro. Things that still need care:
* the ImageFlow package does not work with qt5
* phonon has been removed; we need to write a new player backend based on QtMultimedia
