### ISSUE TITLE
tageditor: unable to enter accented characters for tag values

### ISSUE THREAD

**Issue by supermihi** [maestromusic/maestro#33]
Since using Qt5, I can not enter accented chars (like "É") in the tag editor as tag values. It works in e.g. the browser search field, so the problem must be somewhere in the tag editor widgets.

**Comment by MartinAltmayer** [comment]
For the moment I consider this a bug in Qt https://bugreports.qt.io/browse/QTBUG-44847 . I will wait for a response and maybe write a workaround afterwards. A quick&dirty fix is to set hideEditor to False in line 401 of tagwidgets.py

**Comment by supermihi** [comment]
Appears to work with current Qt version, though the above bugreport is unanswered so far ...
