### ISSUE TITLE
Run noncritical DB-Analyzer fixes on shutdown

### ISSUE THREAD

**Issue by supermihi** [maestromusic/maestro#5]
Non-Critical fixes of the DB analyzer, in particular those that are necessary even in a bug-free operation (e.g. "remove superfluous tag values") should be run automatically when Maestro closes. To that end, it might be reasonable to move the code from the plugin to omg.database because it is a core feature. The fixes that normally should not be necessary, as well as the GUI elements, could remain as plugin.

**Comment by MartinAltmayer** [comment]
Fixed in 464d6ae8f53e3d6ce2939aa8df90a466abd13e2e . Superfluous tags are deleted automatically.
